name: front-tests-workflow

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  jest-test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo "test" >> .env
      - name: run front jest tests
        run: npm i && npm test
      

  #launch docker compose testcafe
  testcafe-e2e-test-front:
    needs: jest-test-front
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code 
        uses: actions/checkout@v2
      # - name: Install TestCafe from 'npm' and Run Tests
      #   uses: DevExpress/testcafe-action@latest
      #   with: 
      #     args: "chrome e2e"
      - name: Launch all required microservices, start front and launch testcafe tests 
        run: docker compose -f docker-compose.testcafe.yml up --build
  docker:
    needs: testcafe-e2e-test-front
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            file: ./Dockerfile
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_CLIENT_IMAGE_NAME}}:latest